# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 330)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QWidget#centralWidget {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox{\n"
"border:1px solid #bababa;  /*边框样式*/\n"
"background-color:#6e6e6e;    /*背景色*/\n"
"}\n"
"QToolTip{\n"
"font-size: 12px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"font-weight: light;\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(200, 200, 200,50);\n"
"}\n"
"QPushButton{\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(200, 200, 200,0);\n"
"}\n"
"\n"
"/* QPushButton 获得焦点时的样式 */\n"
"QPushButton:focus {\n"
"    outline: none;  /* 去除获得焦点时的默认轮廓线 */\n"
"}\n"
"\n"
"/* QPushButton 鼠标悬停时的样式 */\n"
"QPushButton::hover {\n"
"    border-style: solid;  /* 边框样式 */\n"
"    border-width: 0px;  /* 边框宽度 */\n"
"    border-radius: 0px;  /* 边框圆角 */\n"
"    background-color: rgb(165, 165, 165);  /* 鼠标悬停时的背景色 */\n"
"}\n"
"QLabel{\n"
"    font-family: \"Microsoft YaHei\";  /* 字体族 */\n"
"    font-size:14px;\n"
"    font-weight: bold;  /* 字体粗细 */\n"
"    color: white;  /* 文本颜色 */\n"
"    text-align: center center;  /* 文本居中对齐 */\n"
"    indent:0;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    lineedit-password-character: 42;\n"
"    font-size:14px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color:#6e6e6e;\n"
"    font-family: \"Microsoft YaHei\";  /* 字体族 */\n"
"    font-weight: bold;  /* 字体粗细 */\n"
"    color: rgb(165, 165, 165);  /* 文本颜色 */\n"
"    text-align: center center;  /* 文本居中对齐 */\n"
"    font: 14px;\n"
"    indent:0;\n"
"    width: 80px;\n"
"    height: 20px;\n"
"    margin: 0 5px\n"
"\n"
"}\n"
"\n"
"\n"
"/*设置TabWidget中鼠标悬浮在QTabBar的tab上，但未选中该Tab的样式*/\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: rgb(165, 165, 165);\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: white;\n"
"}\n"
"")
        MainWindow.setIconSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.loginBox_body = QtWidgets.QGroupBox(self.centralwidget)
        self.loginBox_body.setMinimumSize(QtCore.QSize(260, 330))
        self.loginBox_body.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.loginBox_body.setTitle("")
        self.loginBox_body.setObjectName("loginBox_body")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loginBox_body)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_top = QtWidgets.QGroupBox(self.loginBox_body)
        self.groupBox_top.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_top.setStyleSheet("#groupBox_top{\n"
"border:none;\n"
"}")
        self.groupBox_top.setTitle("")
        self.groupBox_top.setObjectName("groupBox_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 2, 2, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minButton = QtWidgets.QPushButton(self.groupBox_top)
        self.minButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minButton.setMaximumSize(QtCore.QSize(30, 30))
        self.minButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/global/icon/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton.setIcon(icon)
        self.minButton.setObjectName("minButton")
        self.horizontalLayout_2.addWidget(self.minButton)
        self.closeButton = QtWidgets.QPushButton(self.groupBox_top)
        self.closeButton.setMaximumSize(QtCore.QSize(30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/global/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon1)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_top)
        self.groupBox_fill = QtWidgets.QGroupBox(self.loginBox_body)
        self.groupBox_fill.setStyleSheet("#groupBox_fill{\n"
"    border:none;\n"
"}")
        self.groupBox_fill.setTitle("")
        self.groupBox_fill.setObjectName("groupBox_fill")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_fill)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_fill)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setStyleSheet("#groupBox{\n"
"    background-color:#8b8b8b;\n"
"    border:none;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(10, 0, 10, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.username_login_in = QtWidgets.QLineEdit(self.groupBox)
        self.username_login_in.setMinimumSize(QtCore.QSize(160, 0))
        self.username_login_in.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.username_login_in.setFont(font)
        self.username_login_in.setObjectName("username_login_in")
        self.horizontalLayout_4.addWidget(self.username_login_in)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.password_login_in = QtWidgets.QLineEdit(self.groupBox)
        self.password_login_in.setMinimumSize(QtCore.QSize(160, 0))
        self.password_login_in.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.password_login_in.setFont(font)
        self.password_login_in.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_login_in.setObjectName("password_login_in")
        self.horizontalLayout_5.addWidget(self.password_login_in)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.loginButton = QtWidgets.QPushButton(self.groupBox)
        self.loginButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_4.addWidget(self.loginButton)
        self.foggotButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.foggotButton.setFont(font)
        self.foggotButton.setStyleSheet("")
        self.foggotButton.setObjectName("foggotButton")
        self.verticalLayout_4.addWidget(self.foggotButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setStyleSheet("#groupBox_2{\n"
"    background-color:#8b8b8b;\n"
"    border:none;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(10, 0, 10, 25)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("#label{\n"
"    font-size:14px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.username_sign_up = QtWidgets.QLineEdit(self.groupBox_2)
        self.username_sign_up.setMinimumSize(QtCore.QSize(160, 0))
        self.username_sign_up.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.username_sign_up.setFont(font)
        self.username_sign_up.setObjectName("username_sign_up")
        self.horizontalLayout_6.addWidget(self.username_sign_up)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.password_sign_up = QtWidgets.QLineEdit(self.groupBox_2)
        self.password_sign_up.setMinimumSize(QtCore.QSize(160, 0))
        self.password_sign_up.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.password_sign_up.setFont(font)
        self.password_sign_up.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_sign_up.setObjectName("password_sign_up")
        self.horizontalLayout_7.addWidget(self.password_sign_up)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.bindemail = QtWidgets.QLineEdit(self.groupBox_2)
        self.bindemail.setMinimumSize(QtCore.QSize(160, 0))
        self.bindemail.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.bindemail.setFont(font)
        self.bindemail.setObjectName("bindemail")
        self.horizontalLayout_9.addWidget(self.bindemail)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.CAPTCHA = QtWidgets.QLineEdit(self.groupBox_2)
        self.CAPTCHA.setMinimumSize(QtCore.QSize(0, 0))
        self.CAPTCHA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.CAPTCHA.setFont(font)
        self.CAPTCHA.setObjectName("CAPTCHA")
        self.horizontalLayout_10.addWidget(self.CAPTCHA)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.resendButton = QtWidgets.QPushButton(self.groupBox_2)
        self.resendButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.resendButton.setFont(font)
        self.resendButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.resendButton.setStyleSheet("")
        self.resendButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/global/icon/验证码.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resendButton.setIcon(icon2)
        self.resendButton.setIconSize(QtCore.QSize(20, 20))
        self.resendButton.setObjectName("resendButton")
        self.horizontalLayout_10.addWidget(self.resendButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.signButton = QtWidgets.QPushButton(self.groupBox_2)
        self.signButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.signButton.setFont(font)
        self.signButton.setObjectName("signButton")
        self.verticalLayout_5.addWidget(self.signButton)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.groupBox_fill)
        self.horizontalLayout_8.addWidget(self.loginBox_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.closeButton.clicked.connect(MainWindow.close) # type: ignore
        self.minButton.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "用户名"))
        self.label_2.setText(_translate("MainWindow", "密码"))
        self.loginButton.setText(_translate("MainWindow", "登录"))
        self.loginButton.setShortcut(_translate("MainWindow", "Return"))
        self.foggotButton.setText(_translate("MainWindow", "忘记密码？"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "登录"))
        self.label_3.setText(_translate("MainWindow", "用户名"))
        self.label_4.setText(_translate("MainWindow", "密码"))
        self.label_5.setText(_translate("MainWindow", "绑定邮箱"))
        self.label_6.setText(_translate("MainWindow", "验证"))
        self.resendButton.setToolTip(_translate("MainWindow", "发送验证码"))
        self.signButton.setText(_translate("MainWindow", "注册"))
        self.signButton.setShortcut(_translate("MainWindow", "Return"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "注册"))
import UIqrc_rc
