# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1254, 707)
        MainWindow.setStyleSheet("#mainWindow{\n"
                                 "border:none;\n"
                                 "}\n"
                                 "\n"
                                 "QGroupBox{\n"
                                 "border:1px solid #bababa;  /*边框样式*/\n"
                                 "background-color:#6e6e6e;    /*背景色*/\n"
                                 "}\n"
                                 "\n"
                                 "QToolTip{\n"
                                 "font-size: 12px;\n"
                                 "font-family: \"Microsoft YaHei UI\";\n"
                                 "font-weight: light;\n"
                                 "color:white;\n"
                                 "border-style: solid;\n"
                                 "border-width: 0px;\n"
                                 "border-color: rgba(255, 255, 255, 255);\n"
                                 "background-color: rgba(200, 200, 200,50);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton{\n"
                                 "font-family: \"Microsoft YaHei\";\n"
                                 "font-size: 14px;\n"
                                 "font-weight: bold;\n"
                                 "color:white;\n"
                                 "text-align: center center;\n"
                                 "padding-left: 5px;\n"
                                 "padding-right: 5px;\n"
                                 "padding-top: 4px;\n"
                                 "padding-bottom: 4px;\n"
                                 "border-style: solid;\n"
                                 "border-width: 0px;\n"
                                 "border-color: rgba(255, 255, 255, 255);\n"
                                 "border-radius: 3px;\n"
                                 "background-color: rgba(200, 200, 200,0);\n"
                                 "}\n"
                                 "\n"
                                 "/* QPushButton 获得焦点时的样式 */\n"
                                 "QPushButton:focus {\n"
                                 "    outline: none;  /* 去除获得焦点时的默认轮廓线 */\n"
                                 "}\n"
                                 "\n"
                                 "/* QPushButton 鼠标悬停时的样式 */\n"
                                 "QPushButton::hover {\n"
                                 "    border-style: solid;  /* 边框样式 */\n"
                                 "    border-width: 0px;  /* 边框宽度 */\n"
                                 "    border-radius: 0px;  /* 边框圆角 */\n"
                                 "    background-color: rgb(165, 165, 165);  /* 鼠标悬停时的背景色 */\n"
                                 "}\n"
                                 "\n"
                                 "QLabel{\n"
                                 "    font-family: \"Microsoft YaHei\";  /* 字体族 */\n"
                                 "    font-weight: bold;  /* 字体粗细 */\n"
                                 "    color: white;  /* 文本颜色 */\n"
                                 "    text-align: center center;  /* 文本居中对齐 */\n"
                                 "    indent:0;\n"
                                 "}\n"
                                 "\n"
                                 "QTabWidget::pane {\n"
                                 "    border: none;\n"
                                 "}\n"
                                 "\n"
                                 "QTabBar::tab {\n"
                                 "    background-color:#8b8b8b;\n"
                                 "    font-family: \"Microsoft YaHei\";  /* 字体族 */\n"
                                 "    font-weight: bold;  /* 字体粗细 */\n"
                                 "    color: white;  /* 文本颜色 */\n"
                                 "    text-align: center center;  /* 文本居中对齐 */\n"
                                 "    font: 14px;\n"
                                 "    indent:0;\n"
                                 "    width: 60px;\n"
                                 "    height: 20px;\n"
                                 "    margin: 0px;\n"
                                 "    border-right:1px solid #bababa;\n"
                                 "    border-top-left-radius: 5px;    /*设置tab的边框的圆角（左上圆角）*/\n"
                                 "    border-top-right-radius: 5px;    /*设置tab的边框的圆角（右上圆角）*/\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "/*设置TabWidget中鼠标悬浮在QTabBar的tab上，但未选中该Tab的样式*/\n"
                                 "QTabBar::tab:hover:!selected {\n"
                                 "    background-color: rgb(165, 165, 165);\n"
                                 "}\n"
                                 "\n"
                                 "QTabBar::tab:selected {\n"
                                 "        color: #757575;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox{\n"
                                 "font-family: \"Microsoft YaHei\";\n"
                                 "font-size: 14px;\n"
                                 "color: rgb(218, 218, 218);\n"
                                 "border-width:0px;\n"
                                 "border-color:white;\n"
                                 "border-style:solid;\n"
                                 "background-color: rgba(200, 200, 200,0);\n"
                                 "}\n"
                                 "QComboBox::editable {\n"
                                 "    font-size: 14px;\n"
                                 "    background-color: rgba(200, 200, 200,0);\n"
                                 "}\n"
                                 "QComboBox QAbstractItemView {            \n"
                                 "    scrollbar-width: none; \n"
                                 "    -ms-overflow-style: none; \n"
                                 "}\n"
                                 "QComboBox QAbstractItemView::scrollbar:vertical {\n"
                                 "    width: 0px; /* 隐藏垂直滑动条 */\n"
                                 "    border:none;\n"
                                 "}\n"
                                 "QComboBox QAbstractItemView::scrollbar:horizontal {\n"
                                 "    height: 0px; /* 隐藏水平滑动条 */\n"
                                 "    border:none;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QSlider{\n"
                                 "border-color: #bcbcbc;\n"
                                 "color:#d9d9d9;\n"
                                 "}\n"
                                 "QSlider::groove:horizontal {                                \n"
                                 "     border: 1px solid #999999;                             \n"
                                 "     height: 3px;                                           \n"
                                 "    margin: 0px 0;                                         \n"
                                 "     left: 5px; right: 5px; \n"
                                 " }\n"
                                 "QSlider::handle:horizontal {                               \n"
                                 "     border: 0px ; \n"
                                 "     border-image:url(:/global/icon/圆.png);\n"
                                 "     width:16px;\n"
                                 "     margin: -7px -7px -7px -7px;                  \n"
                                 "} \n"
                                 "QSlider::add-page:horizontal{\n"
                                 "background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
                                 "\n"
                                 "}\n"
                                 "QSlider::sub-page:horizontal{                               \n"
                                 " background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QCheckBox\n"
                                 "{font-size: 16px;\n"
                                 "    font-family: \"Microsoft YaHei\";\n"
                                 "    font-weight: bold;\n"
                                 "         border-radius:9px;\n"
                                 "        background:rgba(66, 195, 255, 0);\n"
                                 "color: rgb(218, 218, 218);;}\n"
                                 "\n"
                                 "QCheckBox::indicator {\n"
                                 "    width: 20px;\n"
                                 "    height: 20px;\n"
                                 "}\n"
                                 "QCheckBox::indicator:unchecked {\n"
                                 "    image: url(:/global/icon/button-off.png);\n"
                                 "}\n"
                                 "\n"
                                 "QCheckBox::indicator:checked {\n"
                                 "    \n"
                                 "    image: url(:/global/icon/button-on.png);\n"
                                 "}\n"
                                 "\n"
                                 "QSplitter::handle {\n"
                                 "    background-color: rgba(200, 200, 200, 0);\n"
                                 "    border: none;\n"
                                 "    border-radius:0px;\n"
                                 "    width: 1px;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "QSplitter::handle:horizontal {\n"
                                 "    border-left:1px solid #bababa; \n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_46.setSpacing(0)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.groupBox_body = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_body.setStyleSheet("")
        self.groupBox_body.setTitle("")
        self.groupBox_body.setObjectName("groupBox_body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_top = QtWidgets.QGroupBox(self.groupBox_body)
        self.groupBox_top.setMinimumSize(QtCore.QSize(0, 35))
        self.groupBox_top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_top.setStyleSheet("#groupBox_top{\n"
                                        "border:none;\n"
                                        "}")
        self.groupBox_top.setTitle("")
        self.groupBox_top.setObjectName("groupBox_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_top)
        self.label.setStyleSheet("font-size:26px;")
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(2, -1, 2, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minButton = QtWidgets.QPushButton(self.groupBox_top)
        self.minButton.setMinimumSize(QtCore.QSize(0, 30))
        self.minButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/global/icon/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton.setIcon(icon)
        self.minButton.setObjectName("minButton")
        self.horizontalLayout_3.addWidget(self.minButton)
        self.maxButton = QtWidgets.QPushButton(self.groupBox_top)
        self.maxButton.setMinimumSize(QtCore.QSize(0, 30))
        self.maxButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/global/icon/正方形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/global/icon/还原.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/global/icon/还原.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.maxButton.setIcon(icon1)
        self.maxButton.setCheckable(True)
        self.maxButton.setObjectName("maxButton")
        self.horizontalLayout_3.addWidget(self.maxButton)
        self.closeButton = QtWidgets.QPushButton(self.groupBox_top)
        self.closeButton.setMinimumSize(QtCore.QSize(0, 30))
        self.closeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/global/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_top)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_body)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.detect_tab = QtWidgets.QWidget()
        self.detect_tab.setObjectName("detect_tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.detect_tab)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_fill = QtWidgets.QGroupBox(self.detect_tab)
        self.groupBox_fill.setStyleSheet("#groupBox_fill{\n"
                                         "border-left:none;\n"
                                         "border-right:none;\n"
                                         "}")
        self.groupBox_fill.setTitle("")
        self.groupBox_fill.setObjectName("groupBox_fill")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_fill)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_fill)
        self.splitter_2.setStyleSheet("")
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_sidebar = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_sidebar.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_sidebar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_sidebar.setStyleSheet("#groupBox_sidebar{\n"
                                            "border:none;\n"
                                            "}")
        self.groupBox_sidebar.setTitle("")
        self.groupBox_sidebar.setObjectName("groupBox_sidebar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_sidebar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setStyleSheet("border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet("font-size:22px;")
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_2.setStyleSheet("#groupBox_2{\n"
                                      "border:none;\n"
                                      "border-top:1px solid #bababa;\n"
                                      "}\n"
                                      "")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_6.setStyleSheet("font-size:18px;")
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.comboBox_task = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_task.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_task.setMaximumSize(QtCore.QSize(120, 16777215))
        self.comboBox_task.setObjectName("comboBox_task")
        self.horizontalLayout_7.addWidget(self.comboBox_task)
        self.comboBox_model = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_model.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_model.setObjectName("comboBox_model")
        self.horizontalLayout_7.addWidget(self.comboBox_model)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_3.setStyleSheet("#groupBox_3{\n"
                                      "border:none;\n"
                                      "}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setStyleSheet("font-size:18px;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.groupBox_input = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_input.setStyleSheet("#groupBox_input{\n"
                                          "border:none;\n"
                                          "}")
        self.groupBox_input.setTitle("")
        self.groupBox_input.setObjectName("groupBox_input")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_input)
        self.horizontalLayout_8.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fileButton = QtWidgets.QPushButton(self.groupBox_input)
        self.fileButton.setMinimumSize(QtCore.QSize(0, 0))
        self.fileButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/detect/icon/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon3)
        self.fileButton.setObjectName("fileButton")
        self.horizontalLayout_8.addWidget(self.fileButton)
        self.cameraButton = QtWidgets.QPushButton(self.groupBox_input)
        self.cameraButton.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/detect/icon/摄像头开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/detect/icon/摄像头关.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(":/detect/icon/摄像头关.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.cameraButton.setIcon(icon4)
        self.cameraButton.setCheckable(True)
        self.cameraButton.setObjectName("cameraButton")
        self.horizontalLayout_8.addWidget(self.cameraButton)
        self.horizontalLayout_9.addWidget(self.groupBox_input)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_4.setStyleSheet("#groupBox_4{\n"
                                      "border:none;\n"
                                      "}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setStyleSheet("font-size:18px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.iouSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.iouSpinBox.setStyleSheet("QDoubleSpinBox{\n"
                                      "background:rgba(200, 200, 200,50);\n"
                                      "color:white;\n"
                                      "font-size: 14px;\n"
                                      "font-family: \"Microsoft YaHei UI\";\n"
                                      "border-style: solid;\n"
                                      "border-width: 1px;\n"
                                      "border-color: rgba(200, 200, 200,100);\n"
                                      "border-radius: 3px;}\n"
                                      "\n"
                                      "QDoubleSpinBox::down-button{\n"
                                      "background:rgba(200, 200, 200,0);\n"
                                      "border-image: url(:/images/icon/箭头_列表展开.png);}\n"
                                      "QDoubleSpinBox::down-button::hover{\n"
                                      "background:rgba(200, 200, 200,100);\n"
                                      "border-image: url(:/images/icon/箭头_列表展开.png);}\n"
                                      "\n"
                                      "QDoubleSpinBox::up-button{\n"
                                      "background:rgba(200, 200, 200,0);\n"
                                      "border-image: url(:/images/icon/箭头_列表收起.png);}\n"
                                      "QDoubleSpinBox::up-button::hover{\n"
                                      "background:rgba(200, 200, 200,100);\n"
                                      "border-image: url(:/images/icon/箭头_列表收起.png);}\n"
                                      "")
        self.iouSpinBox.setMaximum(1.0)
        self.iouSpinBox.setSingleStep(0.01)
        self.iouSpinBox.setProperty("value", 0.2)
        self.iouSpinBox.setObjectName("iouSpinBox")
        self.horizontalLayout_10.addWidget(self.iouSpinBox)
        self.iouSlider = QtWidgets.QSlider(self.groupBox_4)
        self.iouSlider.setStyleSheet("")
        self.iouSlider.setMaximum(100)
        self.iouSlider.setProperty("value", 20)
        self.iouSlider.setOrientation(QtCore.Qt.Horizontal)
        self.iouSlider.setObjectName("iouSlider")
        self.horizontalLayout_10.addWidget(self.iouSlider)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_5.setStyleSheet("#groupBox_5{\n"
                                      "border:none;\n"
                                      "}")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setStyleSheet("font-size:18px;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.confSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.confSpinBox.setStyleSheet("QDoubleSpinBox{\n"
                                       "background:rgba(200, 200, 200,50);\n"
                                       "color:white;\n"
                                       "font-size: 14px;\n"
                                       "font-family: \"Microsoft YaHei UI\";\n"
                                       "border-style: solid;\n"
                                       "border-width: 1px;\n"
                                       "border-color: rgba(200, 200, 200,100);\n"
                                       "border-radius: 3px;}\n"
                                       "\n"
                                       "QDoubleSpinBox::down-button{\n"
                                       "background:rgba(200, 200, 200,0);\n"
                                       "border-image: url(:/images/icon/箭头_列表展开.png);}\n"
                                       "QDoubleSpinBox::down-button::hover{\n"
                                       "background:rgba(200, 200, 200,100);\n"
                                       "border-image: url(:/images/icon/箭头_列表展开.png);}\n"
                                       "\n"
                                       "QDoubleSpinBox::up-button{\n"
                                       "background:rgba(200, 200, 200,0);\n"
                                       "border-image: url(:/images/icon/箭头_列表收起.png);}\n"
                                       "QDoubleSpinBox::up-button::hover{\n"
                                       "background:rgba(200, 200, 200,100);\n"
                                       "border-image: url(:/images/icon/箭头_列表收起.png);}\n"
                                       "")
        self.confSpinBox.setMaximum(1.0)
        self.confSpinBox.setSingleStep(0.01)
        self.confSpinBox.setProperty("value", 0.5)
        self.confSpinBox.setObjectName("confSpinBox")
        self.horizontalLayout_12.addWidget(self.confSpinBox)
        self.confSlider = QtWidgets.QSlider(self.groupBox_5)
        self.confSlider.setStyleSheet("")
        self.confSlider.setMaximum(100)
        self.confSlider.setProperty("value", 50)
        self.confSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider.setObjectName("confSlider")
        self.horizontalLayout_12.addWidget(self.confSlider)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_6.setStyleSheet("#groupBox_6{\n"
                                      "border:none;\n"
                                      "}")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        self.label_11.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_11.setStyleSheet("font-size:18px;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.checkBox_enable = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_enable.setStyleSheet("")
        self.checkBox_enable.setObjectName("checkBox_enable")
        self.horizontalLayout_13.addWidget(self.checkBox_enable)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rateSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.rateSpinBox.setMinimumSize(QtCore.QSize(51, 0))
        self.rateSpinBox.setStyleSheet("QSpinBox{\n"
                                       "background:rgba(200, 200, 200,50);\n"
                                       "color:white;\n"
                                       "font-size: 14px;\n"
                                       "font-family: \"Microsoft YaHei UI\";\n"
                                       "border-style: solid;\n"
                                       "border-width: 1px;\n"
                                       "border-color: rgba(200, 200, 200,100);\n"
                                       "border-radius: 3px;}\n"
                                       "\n"
                                       "QSpinBox::down-button{\n"
                                       "background:rgba(200, 200, 200,0);\n"
                                       "border-image: url(:/images/icon/箭头_列表展开.png);}\n"
                                       "QDoubleSpinBox::down-button::hover{\n"
                                       "background:rgba(200, 200, 200,100);\n"
                                       "border-image: url(:/images/icon/箭头_列表展开.png);}\n"
                                       "\n"
                                       "QSpinBox::up-button{\n"
                                       "background:rgba(200, 200, 200,0);\n"
                                       "border-image: url(:/images/icon/箭头_列表收起.png);}\n"
                                       "QSpinBox::up-button::hover{\n"
                                       "background:rgba(200, 200, 200,100);\n"
                                       "border-image: url(:/images/icon/箭头_列表收起.png);}\n"
                                       "")
        self.rateSpinBox.setMinimum(1)
        self.rateSpinBox.setMaximum(30)
        self.rateSpinBox.setObjectName("rateSpinBox")
        self.horizontalLayout_14.addWidget(self.rateSpinBox)
        self.rateSlider = QtWidgets.QSlider(self.groupBox_6)
        self.rateSlider.setStyleSheet("")
        self.rateSlider.setMinimum(1)
        self.rateSlider.setMaximum(30)
        self.rateSlider.setPageStep(1)
        self.rateSlider.setProperty("value", 1)
        self.rateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider.setObjectName("rateSlider")
        self.horizontalLayout_14.addWidget(self.rateSlider)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_10.setStyleSheet("#groupBox_10{\n"
                                       "border:none;\n"
                                       "}")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_15.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.runButton = QtWidgets.QPushButton(self.groupBox_10)
        self.runButton.setMinimumSize(QtCore.QSize(0, 0))
        self.runButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/detect/icon/运行.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/detect/icon/暂停.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(":/detect/icon/暂停.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.runButton.setIcon(icon5)
        self.runButton.setCheckable(True)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_15.addWidget(self.runButton)
        self.ProgressSlider = QtWidgets.QSlider(self.groupBox_10)
        self.ProgressSlider.setStyleSheet("QSlider {\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    font: 10px;\n"
                                          "    border-radius: 5px;\n"
                                          "    text-align: center;\n"
                                          "    border: none;\n"
                                          "    background-color: rgba(215, 215, 215, 100);\n"
                                          "    height: 15px;\n"
                                          "}\n"
                                          "QSlider::groove:horizontal {\n"
                                          "    border-radius: 5px;\n"
                                          "    border: 1px;\n"
                                          "    height: 8px;\n"
                                          "    margin: 0px;\n"
                                          "    left: 5px; \n"
                                          "    right: 5px;\n"
                                          "}\n"
                                          "\n"
                                          "QSlider::handle:horizontal {\n"
                                          "    border: 0px;\n"
                                          "    width: 15px;\n"
                                          "    border-image:none;\n"
                                          "    margin: -7px -7px -7px -7px;\n"
                                          "}\n"
                                          "QSlider::add-page:horizontal {\n"
                                          "    background: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 rgba(215, 215, 215, 100), stop: 0.25 rgba(215, 215, 215, 100), stop: 0.5 rgba(215, 215, 215, 100), stop: 1 rgba(215, 215, 215, 100));\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QSlider::sub-page:horizontal {\n"
                                          "    background: qlineargradient(spread: pad, x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 rgba(55, 55, 55, 200), stop: 0.25 rgba(55, 55, 55, 200), stop: 0.5 rgba(55, 55, 55, 200), stop: 1 rgba(55, 55, 55, 200));\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "")
        self.ProgressSlider.setMinimum(0)
        self.ProgressSlider.setMaximum(100)
        self.ProgressSlider.setSingleStep(1)
        self.ProgressSlider.setProperty("value", 0)
        self.ProgressSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ProgressSlider.setObjectName("ProgressSlider")
        self.horizontalLayout_15.addWidget(self.ProgressSlider)
        self.detectButton = QtWidgets.QPushButton(self.groupBox_10)
        self.detectButton.setMinimumSize(QtCore.QSize(0, 0))
        self.detectButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/detect/icon/focus (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/detect/icon/focus.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon6.addPixmap(QtGui.QPixmap(":/detect/icon/focus.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.detectButton.setIcon(icon6)
        self.detectButton.setCheckable(True)
        self.detectButton.setChecked(False)
        self.detectButton.setObjectName("detectButton")
        self.horizontalLayout_15.addWidget(self.detectButton)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_11.setStyleSheet("#groupBox_11{\n"
                                       "border:none;\n"
                                       "}")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_13.setStyleSheet("font-size:18px;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        spacerItem3 = QtWidgets.QSpacerItem(166, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.checkBox_male = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_male.setEnabled(True)
        self.checkBox_male.setStyleSheet("")
        self.checkBox_male.setChecked(True)
        self.checkBox_male.setTristate(False)
        self.checkBox_male.setObjectName("checkBox_male")
        self.horizontalLayout_16.addWidget(self.checkBox_male)
        self.checkBox_female = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_female.setStyleSheet("")
        self.checkBox_female.setObjectName("checkBox_female")
        self.horizontalLayout_16.addWidget(self.checkBox_female)
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_12.setMinimumSize(QtCore.QSize(0, 35))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 35))
        self.groupBox_12.setStyleSheet("#groupBox_12{\n"
                                       "border:none;\n"
                                       "border-top:1px solid #bababa;\n"
                                       "border-bottom:1px solid #bababa;\n"
                                       "}")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_17.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.groupBox_12)
        self.label_12.setStyleSheet("font-size:22px;")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        spacerItem4 = QtWidgets.QSpacerItem(254, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_sidebar)
        self.groupBox_13.setStyleSheet("#groupBox_13{\n"
                                       "border:none;\n"
                                       "}")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.detection_info = QtWidgets.QTextEdit(self.groupBox_13)
        self.detection_info.setStyleSheet("background-color: rgba(12, 28, 77, 0);\n"
                                          "\n"
                                          "border-radius:0px;\n"
                                          "font-family: \"Microsoft YaHei\";\n"
                                          "font-size: 12px;\n"
                                          "color: rgb(218, 218, 218);")
        self.detection_info.setReadOnly(True)
        self.detection_info.setObjectName("detection_info")
        self.verticalLayout_9.addWidget(self.detection_info)
        self.verticalLayout_3.addWidget(self.groupBox_13)
        self.groupBox_view = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_view.setStyleSheet("#groupBox_view{\n"
                                         "background-color:#8b8b8b;\n"
                                         "border:none;\n"
                                         "}")
        self.groupBox_view.setTitle("")
        self.groupBox_view.setObjectName("groupBox_view")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_view)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_view)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 41))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_7.setStyleSheet("#groupBox_7{\n"
                                      "background-color:#8b8b8b;\n"
                                      "border:none;\n"
                                      "border-bottom:1px solid #bababa;\n"
                                      "border-radius:0px;\n"
                                      "}")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_11.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setStyleSheet("font-size:22px;")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem5 = QtWidgets.QSpacerItem(857, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.fps_label = QtWidgets.QLabel(self.groupBox_7)
        self.fps_label.setMinimumSize(QtCore.QSize(44, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.fps_label.setFont(font)
        self.fps_label.setStyleSheet("font-size:16px;")
        self.fps_label.setText("")
        self.fps_label.setObjectName("fps_label")
        self.horizontalLayout_11.addWidget(self.fps_label)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_view)
        self.groupBox_15.setStyleSheet("border:none;\n"
                                       "background-color: rgba(200, 200, 200,0)")
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_previous = QtWidgets.QLabel(self.groupBox_15)
        self.label_previous.setStyleSheet("border-right:1px solid #bababa;")
        self.label_previous.setIndent(0)
        self.label_previous.setObjectName("label_previous")
        self.horizontalLayout_27.addWidget(self.label_previous)
        self.label_current = QtWidgets.QLabel(self.groupBox_15)
        self.label_current.setObjectName("label_current")
        self.horizontalLayout_27.addWidget(self.label_current)
        self.verticalLayout_2.addWidget(self.groupBox_15)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_view)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 160))
        self.groupBox_9.setStyleSheet("#groupBox_9{\n"
                                      "background-color: rgba(200, 200, 200,0);\n"
                                      "border:none\n"
                                      ";border-top:1px solid #bababa;\n"
                                      "border-radius:0px;\n"
                                      "}\n"
                                      "")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.report_info = QtWidgets.QTextEdit(self.groupBox_9)
        self.report_info.setStyleSheet("background-color: rgba(200, 200, 200,0);\n"
                                       "border:none;\n"
                                       "font-family: \"Microsoft YaHei\";\n"
                                       "font-size: 14px;\n"
                                       "color: rgb(218, 218, 218);")
        self.report_info.setReadOnly(True)
        self.report_info.setObjectName("report_info")
        self.verticalLayout_10.addWidget(self.report_info)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.horizontalLayout.addWidget(self.splitter_2)
        self.horizontalLayout_5.addWidget(self.groupBox_fill)
        self.tabWidget.addTab(self.detect_tab, "")
        self.report_tab = QtWidgets.QWidget()
        self.report_tab.setObjectName("report_tab")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.report_tab)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setSpacing(0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.groupBox_report_fill = QtWidgets.QGroupBox(self.report_tab)
        self.groupBox_report_fill.setStyleSheet("#groupBox_fill_2{\n"
                                                "border-left:none;\n"
                                                "border-right:none;\n"
                                                "}")
        self.groupBox_report_fill.setTitle("")
        self.groupBox_report_fill.setObjectName("groupBox_report_fill")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_report_fill)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.splitter = QtWidgets.QSplitter(self.groupBox_report_fill)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_report_sidebar = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_report_sidebar.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_report_sidebar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_report_sidebar.setStyleSheet("border:none;\n"
                                                   "\n"
                                                   "")
        self.groupBox_report_sidebar.setTitle("")
        self.groupBox_report_sidebar.setObjectName("groupBox_report_sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_report_sidebar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_report_sidebar)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_8.setStyleSheet("border:none;")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_19.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setStyleSheet("font-size:22px;")
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_19.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_file = QtWidgets.QGroupBox(self.groupBox_report_sidebar)
        self.groupBox_file.setStyleSheet("#groupBox_file{\n"
                                         "border:none;\n"
                                         "border-top:1px solid #bababa;\n"
                                         "}\n"
                                         "")
        self.groupBox_file.setTitle("")
        self.groupBox_file.setObjectName("groupBox_file")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_file)
        self.horizontalLayout_20.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_20.setSpacing(5)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.newButton = QtWidgets.QPushButton(self.groupBox_file)
        self.newButton.setMinimumSize(QtCore.QSize(0, 30))
        self.newButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.newButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/report/icon/new-folder (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newButton.setIcon(icon7)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout_20.addWidget(self.newButton)
        self.openButton = QtWidgets.QPushButton(self.groupBox_file)
        self.openButton.setMinimumSize(QtCore.QSize(0, 30))
        self.openButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.openButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/report/icon/打开.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon8)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_20.addWidget(self.openButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.cutButton = QtWidgets.QPushButton(self.groupBox_file)
        self.cutButton.setMinimumSize(QtCore.QSize(0, 30))
        self.cutButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.cutButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/report/icon/cut (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cutButton.setIcon(icon9)
        self.cutButton.setObjectName("cutButton")
        self.horizontalLayout_20.addWidget(self.cutButton)
        self.copyButton = QtWidgets.QPushButton(self.groupBox_file)
        self.copyButton.setMinimumSize(QtCore.QSize(0, 30))
        self.copyButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.copyButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/report/icon/copy (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyButton.setIcon(icon10)
        self.copyButton.setIconSize(QtCore.QSize(18, 18))
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout_20.addWidget(self.copyButton)
        self.pasteButton = QtWidgets.QPushButton(self.groupBox_file)
        self.pasteButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pasteButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pasteButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/report/icon/clipboard (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pasteButton.setIcon(icon11)
        self.pasteButton.setObjectName("pasteButton")
        self.horizontalLayout_20.addWidget(self.pasteButton)
        self.verticalLayout.addWidget(self.groupBox_file)
        self.groupBox_file_2 = QtWidgets.QGroupBox(self.groupBox_report_sidebar)
        self.groupBox_file_2.setStyleSheet("#groupBox_file_2{\n"
                                           "border:none;\n"
                                           "border-bottom:1px solid #bababa;\n"
                                           "}")
        self.groupBox_file_2.setTitle("")
        self.groupBox_file_2.setObjectName("groupBox_file_2")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.groupBox_file_2)
        self.horizontalLayout_23.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_23.setSpacing(5)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.saveButton = QtWidgets.QPushButton(self.groupBox_file_2)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.saveButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.saveButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/report/icon/floppy-disks (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon12)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_23.addWidget(self.saveButton)
        self.saveasButton = QtWidgets.QPushButton(self.groupBox_file_2)
        self.saveasButton.setMinimumSize(QtCore.QSize(0, 30))
        self.saveasButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.saveasButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/report/icon/floppy-disk-pen (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveasButton.setIcon(icon13)
        self.saveasButton.setObjectName("saveasButton")
        self.horizontalLayout_23.addWidget(self.saveasButton)
        self.printButton = QtWidgets.QPushButton(self.groupBox_file_2)
        self.printButton.setMinimumSize(QtCore.QSize(0, 30))
        self.printButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.printButton.setStyleSheet("")
        self.printButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/report/icon/print (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printButton.setIcon(icon14)
        self.printButton.setObjectName("printButton")
        self.horizontalLayout_23.addWidget(self.printButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem8)
        self.undoButton = QtWidgets.QPushButton(self.groupBox_file_2)
        self.undoButton.setMinimumSize(QtCore.QSize(0, 30))
        self.undoButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.undoButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/report/icon/undo (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoButton.setIcon(icon15)
        self.undoButton.setIconSize(QtCore.QSize(18, 18))
        self.undoButton.setObjectName("undoButton")
        self.horizontalLayout_23.addWidget(self.undoButton)
        self.redoButton = QtWidgets.QPushButton(self.groupBox_file_2)
        self.redoButton.setMinimumSize(QtCore.QSize(0, 30))
        self.redoButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.redoButton.setStyleSheet("")
        self.redoButton.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/report/icon/redo (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoButton.setIcon(icon16)
        self.redoButton.setIconSize(QtCore.QSize(18, 18))
        self.redoButton.setObjectName("redoButton")
        self.horizontalLayout_23.addWidget(self.redoButton)
        self.verticalLayout.addWidget(self.groupBox_file_2)
        self.groupBox_file_3 = QtWidgets.QGroupBox(self.groupBox_report_sidebar)
        self.groupBox_file_3.setStyleSheet("border:none;")
        self.groupBox_file_3.setTitle("")
        self.groupBox_file_3.setObjectName("groupBox_file_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.groupBox_file_3)
        self.horizontalLayout_21.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_21.setSpacing(5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.comboBox_font = QtWidgets.QComboBox(self.groupBox_file_3)
        self.comboBox_font.setMinimumSize(QtCore.QSize(160, 25))
        self.comboBox_font.setMaximumSize(QtCore.QSize(180, 16777215))
        self.comboBox_font.setObjectName("comboBox_font")
        self.horizontalLayout_21.addWidget(self.comboBox_font)
        self.comboBox_size = QtWidgets.QComboBox(self.groupBox_file_3)
        self.comboBox_size.setMinimumSize(QtCore.QSize(50, 25))
        self.comboBox_size.setEditable(True)
        self.comboBox_size.setObjectName("comboBox_size")
        self.horizontalLayout_21.addWidget(self.comboBox_size)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.colorButton = QtWidgets.QPushButton(self.groupBox_file_3)
        self.colorButton.setMinimumSize(QtCore.QSize(0, 30))
        self.colorButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.colorButton.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/report/icon/colour (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorButton.setIcon(icon17)
        self.colorButton.setObjectName("colorButton")
        self.horizontalLayout_21.addWidget(self.colorButton)
        self.verticalLayout.addWidget(self.groupBox_file_3)
        self.groupBox_file_5 = QtWidgets.QGroupBox(self.groupBox_report_sidebar)
        self.groupBox_file_5.setStyleSheet("border:none;")
        self.groupBox_file_5.setTitle("")
        self.groupBox_file_5.setObjectName("groupBox_file_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_file_5)
        self.verticalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(5)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.alignleftButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.alignleftButton.setMinimumSize(QtCore.QSize(0, 30))
        self.alignleftButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.alignleftButton.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/report/icon/left-align (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alignleftButton.setIcon(icon18)
        self.alignleftButton.setObjectName("alignleftButton")
        self.horizontalLayout_24.addWidget(self.alignleftButton)
        self.aligncenterButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.aligncenterButton.setMinimumSize(QtCore.QSize(0, 30))
        self.aligncenterButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.aligncenterButton.setStyleSheet("")
        self.aligncenterButton.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/report/icon/center-align (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aligncenterButton.setIcon(icon19)
        self.aligncenterButton.setObjectName("aligncenterButton")
        self.horizontalLayout_24.addWidget(self.aligncenterButton)
        self.alignrightButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.alignrightButton.setMinimumSize(QtCore.QSize(0, 30))
        self.alignrightButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.alignrightButton.setStyleSheet("")
        self.alignrightButton.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/report/icon/right-align (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alignrightButton.setIcon(icon20)
        self.alignrightButton.setObjectName("alignrightButton")
        self.horizontalLayout_24.addWidget(self.alignrightButton)
        self.alignjustifyButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.alignjustifyButton.setMinimumSize(QtCore.QSize(0, 30))
        self.alignjustifyButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.alignjustifyButton.setStyleSheet("")
        self.alignjustifyButton.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/report/icon/justification (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alignjustifyButton.setIcon(icon21)
        self.alignjustifyButton.setObjectName("alignjustifyButton")
        self.horizontalLayout_24.addWidget(self.alignjustifyButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem10)
        self.bulletlistButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.bulletlistButton.setMinimumSize(QtCore.QSize(0, 30))
        self.bulletlistButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.bulletlistButton.setStyleSheet("")
        self.bulletlistButton.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/report/icon/bullet-list (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bulletlistButton.setIcon(icon22)
        self.bulletlistButton.setIconSize(QtCore.QSize(28, 28))
        self.bulletlistButton.setObjectName("bulletlistButton")
        self.horizontalLayout_24.addWidget(self.bulletlistButton)
        self.numberedlistButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.numberedlistButton.setMinimumSize(QtCore.QSize(0, 30))
        self.numberedlistButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.numberedlistButton.setStyleSheet("")
        self.numberedlistButton.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/report/icon/number-list (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.numberedlistButton.setIcon(icon23)
        self.numberedlistButton.setIconSize(QtCore.QSize(24, 24))
        self.numberedlistButton.setObjectName("numberedlistButton")
        self.horizontalLayout_24.addWidget(self.numberedlistButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(5)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.boldButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.boldButton.setMinimumSize(QtCore.QSize(0, 30))
        self.boldButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.boldButton.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/report/icon/bold (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldButton.setIcon(icon24)
        self.boldButton.setIconSize(QtCore.QSize(18, 18))
        self.boldButton.setCheckable(True)
        self.boldButton.setObjectName("boldButton")
        self.horizontalLayout_26.addWidget(self.boldButton)
        self.italicButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.italicButton.setMinimumSize(QtCore.QSize(0, 30))
        self.italicButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.italicButton.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/report/icon/alphabet (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicButton.setIcon(icon25)
        self.italicButton.setIconSize(QtCore.QSize(18, 18))
        self.italicButton.setCheckable(True)
        self.italicButton.setObjectName("italicButton")
        self.horizontalLayout_26.addWidget(self.italicButton)
        self.underlineButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.underlineButton.setMinimumSize(QtCore.QSize(0, 30))
        self.underlineButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.underlineButton.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/report/icon/underline (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlineButton.setIcon(icon26)
        self.underlineButton.setIconSize(QtCore.QSize(16, 16))
        self.underlineButton.setCheckable(True)
        self.underlineButton.setObjectName("underlineButton")
        self.horizontalLayout_26.addWidget(self.underlineButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem11)
        self.fontzoominButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.fontzoominButton.setMinimumSize(QtCore.QSize(0, 30))
        self.fontzoominButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fontzoominButton.setStyleSheet("")
        self.fontzoominButton.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/report/icon/字体放大.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fontzoominButton.setIcon(icon27)
        self.fontzoominButton.setIconSize(QtCore.QSize(20, 20))
        self.fontzoominButton.setObjectName("fontzoominButton")
        self.horizontalLayout_26.addWidget(self.fontzoominButton)
        self.fontzoomoutButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.fontzoomoutButton.setMinimumSize(QtCore.QSize(0, 30))
        self.fontzoomoutButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.fontzoomoutButton.setStyleSheet("")
        self.fontzoomoutButton.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/report/icon/字体缩小.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fontzoomoutButton.setIcon(icon28)
        self.fontzoomoutButton.setIconSize(QtCore.QSize(20, 20))
        self.fontzoomoutButton.setObjectName("fontzoomoutButton")
        self.horizontalLayout_26.addWidget(self.fontzoomoutButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(5)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.imageButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.imageButton.setMinimumSize(QtCore.QSize(0, 30))
        self.imageButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.imageButton.setStyleSheet("")
        self.imageButton.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/report/icon/image (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageButton.setIcon(icon29)
        self.imageButton.setIconSize(QtCore.QSize(16, 16))
        self.imageButton.setObjectName("imageButton")
        self.horizontalLayout_25.addWidget(self.imageButton)
        self.rotateleftButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.rotateleftButton.setMinimumSize(QtCore.QSize(0, 30))
        self.rotateleftButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rotateleftButton.setStyleSheet("")
        self.rotateleftButton.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/report/icon/rotate-left (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateleftButton.setIcon(icon30)
        self.rotateleftButton.setIconSize(QtCore.QSize(14, 14))
        self.rotateleftButton.setObjectName("rotateleftButton")
        self.horizontalLayout_25.addWidget(self.rotateleftButton)
        self.rotaterightButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.rotaterightButton.setMinimumSize(QtCore.QSize(0, 30))
        self.rotaterightButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.rotaterightButton.setStyleSheet("")
        self.rotaterightButton.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/report/icon/rotate-right (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotaterightButton.setIcon(icon31)
        self.rotaterightButton.setIconSize(QtCore.QSize(14, 14))
        self.rotaterightButton.setObjectName("rotaterightButton")
        self.horizontalLayout_25.addWidget(self.rotaterightButton)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem12)
        self.imageZoomInButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.imageZoomInButton.setMinimumSize(QtCore.QSize(0, 30))
        self.imageZoomInButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.imageZoomInButton.setStyleSheet("")
        self.imageZoomInButton.setText("")
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/report/icon/图像放大.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageZoomInButton.setIcon(icon32)
        self.imageZoomInButton.setIconSize(QtCore.QSize(24, 24))
        self.imageZoomInButton.setObjectName("imageZoomInButton")
        self.horizontalLayout_25.addWidget(self.imageZoomInButton)
        self.imageZoomOutButton = QtWidgets.QPushButton(self.groupBox_file_5)
        self.imageZoomOutButton.setMinimumSize(QtCore.QSize(0, 30))
        self.imageZoomOutButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.imageZoomOutButton.setStyleSheet("")
        self.imageZoomOutButton.setText("")
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/report/icon/图像缩小.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageZoomOutButton.setIcon(icon33)
        self.imageZoomOutButton.setIconSize(QtCore.QSize(24, 24))
        self.imageZoomOutButton.setObjectName("imageZoomOutButton")
        self.horizontalLayout_25.addWidget(self.imageZoomOutButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        self.verticalLayout.addWidget(self.groupBox_file_5)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.report_view = QtWidgets.QGroupBox(self.splitter)
        self.report_view.setStyleSheet("#report_view{\n"
                                       "background-color:#8b8b8b;\n"
                                       "border:none;\n"
                                       "}")
        self.report_view.setTitle("")
        self.report_view.setObjectName("report_view")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.report_view)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.textEdit = QtWidgets.QTextEdit(self.report_view)
        self.textEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textEdit.setStyleSheet("")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_22.addWidget(self.textEdit)
        self.horizontalLayout_18.addWidget(self.splitter)
        self.horizontalLayout_47.addWidget(self.groupBox_report_fill)
        self.tabWidget.addTab(self.report_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_48.setSpacing(0)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_35.setObjectName("groupBox_35")
        self.horizontalLayout_48.addWidget(self.groupBox_35)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.groupBox_bottom = QtWidgets.QGroupBox(self.groupBox_body)
        self.groupBox_bottom.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_bottom.setStyleSheet("#groupBox_bottom{\n"
                                           "border:none;\n"
                                           "}")
        self.groupBox_bottom.setTitle("")
        self.groupBox_bottom.setObjectName("groupBox_bottom")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_bottom)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_bottom = QtWidgets.QLabel(self.groupBox_bottom)
        self.label_bottom.setMinimumSize(QtCore.QSize(0, 30))
        self.label_bottom.setText("")
        self.label_bottom.setObjectName("label_bottom")
        self.horizontalLayout_4.addWidget(self.label_bottom)
        self.verticalLayout_4.addWidget(self.groupBox_bottom)
        self.horizontalLayout_46.addWidget(self.groupBox_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_task.setCurrentIndex(-1)
        self.closeButton.clicked.connect(MainWindow.close)  # type: ignore
        self.minButton.clicked.connect(MainWindow.showMinimized)  # type: ignore
        self.maxButton.clicked.connect(MainWindow.showMaximized)  # type: ignore
        self.undoButton.clicked.connect(self.textEdit.undo)  # type: ignore
        self.redoButton.clicked.connect(self.textEdit.redo)  # type: ignore
        self.cutButton.clicked.connect(self.textEdit.cut)  # type: ignore
        self.copyButton.clicked.connect(self.textEdit.copy)  # type: ignore
        self.pasteButton.clicked.connect(self.textEdit.paste)  # type: ignore
        self.fontzoominButton.clicked.connect(self.textEdit.zoomIn)  # type: ignore
        self.fontzoomoutButton.clicked.connect(self.textEdit.zoomOut)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "骨龄评估"))
        self.label_3.setText(_translate("MainWindow", "设置"))
        self.label_6.setText(_translate("MainWindow", "模式选择"))
        self.label_7.setText(_translate("MainWindow", "输入选择"))
        self.fileButton.setToolTip(_translate("MainWindow", "打开"))
        self.cameraButton.setToolTip(_translate("MainWindow", "摄像头"))
        self.label_8.setText(_translate("MainWindow", "IoU"))
        self.label_10.setText(_translate("MainWindow", "置信度"))
        self.label_11.setText(_translate("MainWindow", "帧间延时"))
        self.checkBox_enable.setText(_translate("MainWindow", "启用"))
        self.runButton.setToolTip(_translate("MainWindow", "运行/暂停"))
        self.detectButton.setToolTip(_translate("MainWindow", "检测"))
        self.label_13.setText(_translate("MainWindow", "性别"))
        self.checkBox_male.setText(_translate("MainWindow", "男"))
        self.checkBox_female.setText(_translate("MainWindow", "女"))
        self.label_12.setText(_translate("MainWindow", "预测情况"))
        self.label_9.setText(_translate("MainWindow", "视图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.detect_tab), _translate("MainWindow", "推理区"))
        self.label_4.setText(_translate("MainWindow", "设置"))
        self.newButton.setToolTip(_translate("MainWindow", "新建"))
        self.newButton.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.openButton.setToolTip(_translate("MainWindow", "打开"))
        self.openButton.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.cutButton.setToolTip(_translate("MainWindow", "剪切"))
        self.cutButton.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.copyButton.setToolTip(_translate("MainWindow", "复制"))
        self.copyButton.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pasteButton.setToolTip(_translate("MainWindow", "粘贴"))
        self.pasteButton.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.saveButton.setToolTip(_translate("MainWindow", "保存"))
        self.saveButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.saveasButton.setToolTip(_translate("MainWindow", "另存为"))
        self.saveasButton.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.printButton.setToolTip(_translate("MainWindow", "打印"))
        self.printButton.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.undoButton.setToolTip(_translate("MainWindow", "撤销"))
        self.undoButton.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.redoButton.setToolTip(_translate("MainWindow", "重做"))
        self.redoButton.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.comboBox_font.setToolTip(_translate("MainWindow", "字体"))
        self.comboBox_size.setToolTip(_translate("MainWindow", "字号"))
        self.colorButton.setToolTip(_translate("MainWindow", "字体颜色"))
        self.alignleftButton.setToolTip(_translate("MainWindow", "左对齐"))
        self.alignleftButton.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.aligncenterButton.setToolTip(_translate("MainWindow", "居中对齐"))
        self.aligncenterButton.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.alignrightButton.setToolTip(_translate("MainWindow", "右对齐"))
        self.alignrightButton.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.alignjustifyButton.setToolTip(_translate("MainWindow", "两端对齐"))
        self.alignjustifyButton.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.bulletlistButton.setToolTip(_translate("MainWindow", "无序编号"))
        self.numberedlistButton.setToolTip(_translate("MainWindow", "数字编号"))
        self.boldButton.setToolTip(_translate("MainWindow", "粗体"))
        self.boldButton.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.italicButton.setToolTip(_translate("MainWindow", "斜体"))
        self.italicButton.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.underlineButton.setToolTip(_translate("MainWindow", "下划线"))
        self.underlineButton.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.fontzoominButton.setToolTip(_translate("MainWindow", "右旋转"))
        self.fontzoominButton.setShortcut(_translate("MainWindow", "Ctrl+]"))
        self.fontzoomoutButton.setToolTip(_translate("MainWindow", "右旋转"))
        self.fontzoomoutButton.setShortcut(_translate("MainWindow", "Ctrl+["))
        self.imageButton.setToolTip(_translate("MainWindow", "插入图片"))
        self.rotateleftButton.setToolTip(_translate("MainWindow", "左旋转"))
        self.rotaterightButton.setToolTip(_translate("MainWindow", "右旋转"))
        self.imageZoomInButton.setToolTip(_translate("MainWindow", "右旋转"))
        self.imageZoomOutButton.setToolTip(_translate("MainWindow", "右旋转"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.report_tab), _translate("MainWindow", "报告区"))
        self.groupBox_35.setTitle(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "其他"))


import UIqrc_rc
