# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resetUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(260, 330)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QWidget#centralWidget {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QGroupBox{\n"
"border:1px solid #bababa;  /*边框样式*/\n"
"background-color:#6e6e6e;    /*背景色*/\n"
"}\n"
"QToolTip{\n"
"font-size: 12px;\n"
"font-family: \"Microsoft YaHei UI\";\n"
"font-weight: light;\n"
"color:white;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"background-color: rgba(200, 200, 200,50);\n"
"}\n"
"QPushButton{\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(200, 200, 200,0);\n"
"}\n"
"\n"
"/* QPushButton 获得焦点时的样式 */\n"
"QPushButton:focus {\n"
"    outline: none;  /* 去除获得焦点时的默认轮廓线 */\n"
"}\n"
"\n"
"/* QPushButton 鼠标悬停时的样式 */\n"
"QPushButton::hover {\n"
"    border-style: solid;  /* 边框样式 */\n"
"    border-width: 0px;  /* 边框宽度 */\n"
"    border-radius: 0px;  /* 边框圆角 */\n"
"    background-color: rgb(165, 165, 165);  /* 鼠标悬停时的背景色 */\n"
"}\n"
"QLabel{\n"
"    font-family: \"Microsoft YaHei\";  /* 字体族 */\n"
"    font-size:14px;\n"
"    font-weight: bold;  /* 字体粗细 */\n"
"    color: white;  /* 文本颜色 */\n"
"    text-align: center center;  /* 文本居中对齐 */\n"
"    indent:0;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    lineedit-password-character: 42;\n"
"    font-size:14px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color:#6e6e6e;\n"
"    font-family: \"Microsoft YaHei\";  /* 字体族 */\n"
"    font-weight: bold;  /* 字体粗细 */\n"
"    color: rgb(165, 165, 165);  /* 文本颜色 */\n"
"    text-align: center center;  /* 文本居中对齐 */\n"
"    font: 14px;\n"
"    indent:0;\n"
"    width: 80px;\n"
"    height: 20px;\n"
"    margin: 0 5px\n"
"\n"
"}\n"
"\n"
"\n"
"/*设置TabWidget中鼠标悬浮在QTabBar的tab上，但未选中该Tab的样式*/\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: rgb(165, 165, 165);\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: white;\n"
"}\n"
"\n"
"")
        MainWindow.setIconSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.resetBox_body = QtWidgets.QGroupBox(self.centralwidget)
        self.resetBox_body.setMinimumSize(QtCore.QSize(260, 330))
        self.resetBox_body.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.resetBox_body.setTitle("")
        self.resetBox_body.setObjectName("resetBox_body")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.resetBox_body)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_top = QtWidgets.QGroupBox(self.resetBox_body)
        self.groupBox_top.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_top.setStyleSheet("#groupBox_top{\n"
"border:none;\n"
"}")
        self.groupBox_top.setTitle("")
        self.groupBox_top.setObjectName("groupBox_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 2, 2, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minButton = QtWidgets.QPushButton(self.groupBox_top)
        self.minButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minButton.setMaximumSize(QtCore.QSize(30, 30))
        self.minButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/global/icon/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton.setIcon(icon)
        self.minButton.setObjectName("minButton")
        self.horizontalLayout_2.addWidget(self.minButton)
        self.closeButton = QtWidgets.QPushButton(self.groupBox_top)
        self.closeButton.setMaximumSize(QtCore.QSize(30, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/global/icon/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon1)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_top)
        self.groupBox_fill = QtWidgets.QGroupBox(self.resetBox_body)
        self.groupBox_fill.setStyleSheet("#groupBox_fill{\n"
"    border:none;\n"
"}")
        self.groupBox_fill.setTitle("")
        self.groupBox_fill.setObjectName("groupBox_fill")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_fill)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_remake = QtWidgets.QGroupBox(self.groupBox_fill)
        self.groupBox_remake.setStyleSheet("#groupBox_remake{\n"
"    background-color:#8b8b8b;\n"
"    border:none;\n"
"}")
        self.groupBox_remake.setObjectName("groupBox_remake")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_remake)
        self.verticalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox_remake)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.email = QtWidgets.QLineEdit(self.groupBox_remake)
        self.email.setMinimumSize(QtCore.QSize(160, 0))
        self.email.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.horizontalLayout_11.addWidget(self.email)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.groupBox_remake)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.CAPTCHA = QtWidgets.QLineEdit(self.groupBox_remake)
        self.CAPTCHA.setMinimumSize(QtCore.QSize(0, 0))
        self.CAPTCHA.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.CAPTCHA.setFont(font)
        self.CAPTCHA.setObjectName("CAPTCHA")
        self.horizontalLayout_12.addWidget(self.CAPTCHA)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.resendButton = QtWidgets.QPushButton(self.groupBox_remake)
        self.resendButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.resendButton.setFont(font)
        self.resendButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.resendButton.setStyleSheet("")
        self.resendButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/global/icon/验证码.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resendButton.setIcon(icon2)
        self.resendButton.setIconSize(QtCore.QSize(20, 20))
        self.resendButton.setObjectName("resendButton")
        self.horizontalLayout_12.addWidget(self.resendButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.groupBox_remake)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.password_reset = QtWidgets.QLineEdit(self.groupBox_remake)
        self.password_reset.setMinimumSize(QtCore.QSize(160, 0))
        self.password_reset.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.password_reset.setFont(font)
        self.password_reset.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_reset.setObjectName("password_reset")
        self.horizontalLayout_13.addWidget(self.password_reset)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.groupBox_remake)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.password_reset_2 = QtWidgets.QLineEdit(self.groupBox_remake)
        self.password_reset_2.setMinimumSize(QtCore.QSize(160, 0))
        self.password_reset_2.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.password_reset_2.setFont(font)
        self.password_reset_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_reset_2.setObjectName("password_reset_2")
        self.horizontalLayout_14.addWidget(self.password_reset_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.resetButton = QtWidgets.QPushButton(self.groupBox_remake)
        self.resetButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_6.addWidget(self.resetButton)
        spacerItem9 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_3.addWidget(self.groupBox_remake)
        self.verticalLayout_2.addWidget(self.groupBox_fill)
        self.horizontalLayout_4.addWidget(self.resetBox_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.closeButton.clicked.connect(MainWindow.close) # type: ignore
        self.minButton.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "邮箱"))
        self.label_8.setText(_translate("MainWindow", "验证"))
        self.resendButton.setToolTip(_translate("MainWindow", "发送验证码"))
        self.label_9.setText(_translate("MainWindow", "新密码"))
        self.label_10.setText(_translate("MainWindow", "确认密码"))
        self.resetButton.setText(_translate("MainWindow", "重置密码"))
        self.resetButton.setShortcut(_translate("MainWindow", "Return"))
import UIqrc_rc
